{{- define "platform.cronjob" -}}
{{- if .Values.cronJob.enabled }}
{{- $cronInitContainers := list -}}
{{- $cronInitCfg := .Values.cronJob.initContainers -}}
{{- if $cronInitCfg }}
  {{- if kindIs "slice" $cronInitCfg }}
    {{- range $cronInitCfg }}
      {{- $cronInitContainers = append $cronInitContainers . -}}
    {{- end }}
  {{- else if kindIs "map" $cronInitCfg }}
    {{- if and $cronInitCfg.enabled $cronInitCfg.containers }}
      {{- range $cronInitCfg.containers }}
        {{- $cronInitContainers = append $cronInitContainers . -}}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $cronSidecars := list -}}
{{- if and .Values.cronJob.sidecars .Values.cronJob.sidecars.enabled .Values.cronJob.sidecars.containers }}
  {{- range .Values.cronJob.sidecars.containers }}
    {{- $cronSidecars = append $cronSidecars . -}}
  {{- end }}
{{- end }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "platform.fullname" . }}-cron
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- if .Values.cronJob.annotations }}
  annotations:
    {{- range $k, $v := .Values.cronJob.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronJob.concurrencyPolicy | default "Allow" }}
  {{- if .Values.cronJob.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.cronJob.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cronJob.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronJob.failedJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.cronJob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronJob.startingDeadlineSeconds }}
  {{- end }}
  suspend: {{ .Values.cronJob.suspend | default false }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "platform.selectorLabels" . | nindent 12 }}
            {{- range $k, $v := .Values.commonLabels }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
            {{- range $k, $v := .Values.cronJob.podLabels }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
          {{- if .Values.cronJob.podAnnotations }}
          annotations:
            {{- range $k, $v := .Values.cronJob.podAnnotations }}
            {{ $k }}: {{ $v | quote }}
            {{- end }}
          {{- end }}
        spec:
          serviceAccountName: {{ include "platform.serviceAccountName" . }}
          restartPolicy: OnFailure
          {{- if .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- range .Values.global.imagePullSecrets }}
            - name: {{ . }}
            {{- end }}
          {{- end }}
          {{- if gt (len $cronInitContainers) 0 }}
          initContainers: {{- toYaml $cronInitContainers | nindent 10 }}
          {{- end }}
          {{- if .Values.cronJob.containers }}
          containers: {{- toYaml .Values.cronJob.containers | nindent 10 }}
          {{- else }}
            {{- $defaultCronContainer := dict "name" (printf "%s-cron" (include "platform.name" .)) "image" (include "platform.image" .) "imagePullPolicy" (include "platform.imagePullPolicy" .) -}}
            {{- $cronContainers := list $defaultCronContainer -}}
            {{- range $cronSidecars }}
              {{- $cronContainers = append $cronContainers . -}}
            {{- end }}
          containers: {{- toYaml $cronContainers | nindent 10 }}
          {{- end }}
          {{- if .Values.cronJob.volumes }}
          volumes: {{- toYaml .Values.cronJob.volumes | nindent 10 }}
          {{- end }}
          {{- if .Values.cronJob.nodeSelector }}
          nodeSelector: {{- toYaml .Values.cronJob.nodeSelector | nindent 10 }}
          {{- end }}
          {{- if .Values.cronJob.tolerations }}
          tolerations: {{- toYaml .Values.cronJob.tolerations | nindent 10 }}
          {{- end }}
{{- end }}
{{- end }}
