{{- define "platform.daemonset" -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "platform.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- range $k, $v := .Values.labels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.annotations }}
  annotations:
    {{- range $k, $v := .Values.commonAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    {{- range $k, $v := .Values.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
  {{- if .Values.daemonSet.updateStrategy }}
  updateStrategy: {{- toYaml .Values.daemonSet.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    {{- include "platform.podTemplateSpec" . | nindent 4 }}
{{- end }}

