{{- if and .Values.tlsSelfSigned.enabled .Values.ingress.hostname -}}
{{- $cn := default .Values.ingress.hostname .Values.tlsSelfSigned.commonName -}}
{{- $dnsNames := .Values.tlsSelfSigned.dnsNames -}}
{{- if not $dnsNames }}
  {{- $dnsNames = list .Values.ingress.hostname -}}
{{- end }}
{{- $ca := genCA (printf "%s-ca" (include "platform.fullname" .)) .Values.tlsSelfSigned.validityDays -}}
{{- $cert := genSignedCert $cn nil $dnsNames .Values.tlsSelfSigned.validityDays $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (include "platform.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- range $k, $v := .Values.commonAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
