{{- if and .Values.ingress.enabled .Values.ingress.secrets }}
{{- range .Values.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "platform.labels" $ | nindent 4 }}
    {{- range $k, $v := $.Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- if $.Values.commonAnnotations }}
  annotations:
    {{- range $k, $v := $.Values.commonAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
