apiVersion: v2
name: my-test-service
description: A Helm chart for my-test-service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: platform
    version: 1.0.0
    repository: file://../platform-library
    import-values:
      - defaults
